### ISSUE TITLE
Tracking issue for supporting all GitHub webhook events

### ISSUE THREAD

**Issue by tisonkun** [tisonkun/gravity#1]
## Reference

* [GitHub WebHook's document](https://docs.github.com/en/developers/webhooks-and-events/webhooks/about-webhooks)
* Existing work: [go-playground/webhooks](https://github.com/go-playground/webhooks), especially for its [payloads' definition](https://github.com/go-playground/webhooks/blob/master/github/payload.go).

## How-to

1. Extend the `Payload` enum with new event.

https://github.com/tisonkun/gravity/blob/86361a10b9d82a5ccb8b4fb594af8578cce43a5d/src/payload/mod.rs#L24-L39

2. Add the data structure as `IssuesEvent`. All reusable models placed under `src/payload/model.rs`. For how to define a data structure, see also existing structs.
3. Add convertor lookup in `src/payload/mod.rs`.

https://github.com/tisonkun/gravity/blob/86361a10b9d82a5ccb8b4fb594af8578cce43a5d/src/payload/mod.rs#L54-L73

Tips:

* Tests are appreciated! See also `tests` folder about how to test the data structure.
* You can test the webhook server by yourself:
  * https://smee.io/ provides a webhook proxy.
  * [Create you own webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks) and [test it](https://docs.github.com/en/developers/webhooks-and-events/webhooks/testing-webhooks) follow the reference, using the proxy generated from smee.io as the webhook target url.
  * Be sure to [configure a webhook secret](https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks) and set up the environment variable `WEBHOOK_SECRET`.

## Subtasks

* [x] #2
* [x] #3
* [x] #4
* [x] #5
* [x] #6
* [x] #7
* [x] #9
* [x] #8
* [x] #10
* [x] #11
* [x] #12
* [x] #13
* [x] #14
* [x] #15
* [x] #16
* [x] #17
* [x] #18
* [x] #19
* [x] #20
* [x] #21
* [x] #22
* [x] #23
* [x] #24
* [x] #25
* [x] #26
* [x] #27
* [x] #28
* [x] #29
* [x] #30
* [x] #31
* [x] #32
* [x] #33
* [x] #34
* [x] #35
* [x] #36
* [x] #37
* [x] #38
* [x] #48
* [x] #39
* [x] #40
* [x] #41
* [x] #42
* [x] #43
* [x] #44
* [x] #45

**Comment by Mini256** [comment]
🤔 How about generating payload definition according to the official [payload schema](https://github.com/octokit/webhooks/tree/master/payload-schemas).

**Comment by tisonkun** [comment]
Closed as all subtasks done.
